galaxy_info:
  author: Muhammad Panji
  description: install tmux
  company: howtodojo.com
  license: BSD
  min_ansible_version: 2.0
  github_branch: master
  platforms:
  - name: Ubuntu
    versions:
     - precise
     - trusty
     - xenial

  galaxy_tags:
    - monitoring
    - tmux

dependencies: []
